# Generated by Django 5.2.6 on 2025-09-07 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_maquina', models.CharField(max_length=50, unique=True)),
                ('nombre_maquina', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RECREATIVA', 'Recreativa'), ('VENDING', 'Vending'), ('GRUA', 'Grúa'), ('REDEMPTION', 'Redemption'), ('OTRA', 'Otra')], max_length=20)),
                ('precio_juego', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.salajuegos')),
            ],
        ),
    ]
