# Generated by Django 5.2.6 on 2025-09-07 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recaudacion', models.DateTimeField(auto_now_add=True)),
                ('contador_anterior', models.BigIntegerField()),
                ('contador_actual', models.BigIntegerField()),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaudaciones', to='gestion.maquina')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
