# Generated by Django 5.2.6 on 2025-09-13 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_recaudacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='tipo',
        ),
        migrations.AddField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(choices=[('ENTRETENIMIENTO', 'Entretenimiento'), ('VENDING', 'Vending'), ('OTRA', 'Otra')], default='ENTRETENIMIENTO', max_length=50),
        ),
        migrations.AddField(
            model_name='maquina',
            name='subtipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas', to='gestion.salajuegos'),
        ),
    ]
