# Generated by Django 5.2.6 on 2025-09-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cargamercaderia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargamercaderia',
            old_name='cantidad',
            new_name='cantidad_cargada',
        ),
        migrations.AddField(
            model_name='cargamercaderia',
            name='stock_final',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargamercaderia',
            name='stock_inicial',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargamercaderia',
            name='producto_nombre',
            field=models.CharField(default='Producto', max_length=200),
        ),
    ]
