# Generated by Django 5.2.6 on 2025-09-14 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_mantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='capacidad_producto',
            field=models.PositiveIntegerField(default=0, help_text='La cantidad fija que debe llevar la máquina de este producto.'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='producto_en_maquina',
            field=models.CharField(blank=True, help_text='Ej: Peluche Capibara, Coca-Cola 500ml', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RegistroInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('stock_encontrado', models.PositiveIntegerField(help_text='Cantidad que queda en la máquina al llegar.')),
                ('cantidad_repuesta', models.PositiveIntegerField(help_text='Cantidad de producto nuevo que se añadió.')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestion.maquina')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CargaMercaderia',
        ),
    ]
